services:
  localstack:
    container_name: makeen-challenge-localstack-test
    image: localstack/localstack-pro:4.4
    ports:
      - "4567:4566" # LocalStack Gateway
      - "4600-4649:4510-4559" # External services port range
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - SERVICES=dynamodb,lambda,apigateway,cloudwatch,s3,iam,logs,cloudformation,ssm,ecr,s3
      - LOCALSTACK_AUTH_TOKEN=ls-NAyIXEnU-hAPU-9943-Taku-VUbA945853a3
      - DEFAULT_REGION=eu-central-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      makeen-network-test:
        ipv4_address: 172.30.0.5

  # Container that deploy CDK in localstack
  infra:
    container_name: makeen-challenge-infra-test
    build:
      context: ./infra
      dockerfile: Dockerfile
    environment:
      - AWS_ENVAR_ALLOWLIST=AWS_REGION
      - AWS_ENDPOINT_URL=http://172.30.0.5:4566
      - AWS_ENDPOINT_URL_S3=http://172.30.0.5:4566
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-central-1
      - STAGE=dev
      # This environment variables will be used by localstack for lambdas hot-reloading
      - ROOT_FOLDER_PATH=${PWD}
    volumes:
      - ./infra:/infra
      - /infra/node_modules
      - ./apps/authorizers/api-key-authorizer/dist:/apps/authorizers/api-key-authorizer/dist
      - ./apps/text-file-processor/dist:/apps/text-file-processor/dist
    depends_on:
      localstack:
        condition: service_healthy
    # Set the DNS server to be the LocalStack container
    dns:
      - 172.30.0.5
    networks:
      - makeen-network-test

networks:
  makeen-network-test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
