version: "3"

# Taskfile for makeen-challenge project
# Provides tasks for managing Docker Compose, LocalStack, and CDK deployments

includes:
  infra:
    taskfile: ./infra/Taskfile.yml
    dir: ./infra
  tfp:
    aliases:
      - text-file-processor
    taskfile: ./apps/text-file-processor/Taskfile.yml
    dir: ./apps/text-file-processor
  auth:
    taskfile: ./apps/authorizers/api-key-authorizer/Taskfile.yml
    dir: ./apps/authorizers/api-key-authorizer

tasks:
  localstack:log:
    desc: View LocalStack container logs
    cmd: docker-compose -p makeen_dev -f docker-compose.dev.yml logs -f localstack

  infra:log:
    desc: View infra container logs
    cmd: docker-compose -p makeen_dev -f docker-compose.dev.yml logs -f infra

  wait-for-infra:
    desc: Waits for the 'infra' service container to complete deployment and exit successfully.
    requires:
      vars:
        - DOCKER_COMPOSE_FILE
        - DOCKER_PROJECT_NAME
    env:
      DOCKER_COMPOSE_FILE: "{{.DOCKER_COMPOSE_FILE}}"
      DOCKER_PROJECT_NAME_ENV: "{{.DOCKER_PROJECT_NAME}}"
    cmds:
      - |
        echo "INFO: Waiting for 'infra' container to disappear (complete its run) for project '$DOCKER_PROJECT_NAME_ENV'..."
        MAX_ATTEMPTS=36 # Approx 3 minutes (36 * 5s)
        ATTEMPT_NUM=1
        INFRA_SERVICE_NAME="infra"

        while [ "$ATTEMPT_NUM" -le "$MAX_ATTEMPTS" ]; do
          # Check if the infra container is listed by docker-compose ps -q
          # If it's empty, the container is gone.
          INFRA_CONTAINER_PRESENCE=$(docker-compose -p "$DOCKER_PROJECT_NAME_ENV" -f "$DOCKER_COMPOSE_FILE" ps -q "$INFRA_SERVICE_NAME")

          if [ -z "$INFRA_CONTAINER_PRESENCE" ]; then
            echo "INFO: 'infra' container has disappeared. Assuming successful completion."
            exit 0
          else
            echo "INFO: Attempt $ATTEMPT_NUM/$MAX_ATTEMPTS: 'infra' container (ID(s): $INFRA_CONTAINER_PRESENCE) is still present. Waiting for it to disappear. Retrying in 5s..."
          fi
          sleep 5
          ATTEMPT_NUM=$((ATTEMPT_NUM + 1))
        done

        echo "ERROR: Timeout waiting for 'infra' container to disappear after $MAX_ATTEMPTS attempts."
        INFRA_CONTAINER_FINAL_CHECK=$(docker-compose -p "$DOCKER_PROJECT_NAME_ENV" -f "$DOCKER_COMPOSE_FILE" ps -q "$INFRA_SERVICE_NAME")
        if [ ! -z "$INFRA_CONTAINER_FINAL_CHECK" ]; then
          echo "INFO: 'infra' container (ID(s): $INFRA_CONTAINER_FINAL_CHECK) was still present at timeout."
          echo "INFO: Dumping logs for diagnostics (note: this might be for a new instance if previous one exited and compose tried to restart, though restart policy was removed):"
          # Iterate over potentially multiple IDs if service scales (though not expected for 'infra')
          for id in $INFRA_CONTAINER_FINAL_CHECK; do
            echo "--- Logs for container $id ---"
            docker logs "$id" 2>/dev/null || echo "Failed to retrieve logs for $id."
          done
        else
          echo "INFO: 'infra' container was not found during final check either (this is unexpected if timeout occurred due to presence)."
        fi
        exit 1
    internal: true
    silent: true

  dev:build:
    desc: Build all services
    deps:
      - infra:build
      - tfp:build
      - auth:build
    internal: true

  dev:run:
    desc: Start the development environment
    aliases:
      - run
    deps:
      - dev:build
    cmds:
      - docker-compose -p makeen_dev -f docker-compose.dev.yml up -d --build
      - task: wait-for-infra
        vars:
          DOCKER_COMPOSE_FILE: docker-compose.dev.yml
          DOCKER_PROJECT_NAME: makeen_dev
      - task: tfp:dev:run

  dev:destroy:
    desc: |
      Destroy development environment
      Note: the whole infra will be destroyed as we're also deleting localstack volume
    aliases:
      - destroy
    cmds:
      - docker-compose -p makeen_dev -f docker-compose.dev.yml down -v

  test:e2e:run:
    desc: Run end-to-end tests with LocalStack
    deps:
      - dev:build
    cmds:
      - docker compose -p makeen_test -f docker-compose.testing.yml up -d
      - task: wait-for-infra
        vars:
          DOCKER_COMPOSE_FILE: docker-compose.testing.yml
          DOCKER_PROJECT_NAME: makeen_test
      - task: tfp:test:e2e:run

  test:e2e:destroy:
    desc: Destroy testing environment
    aliases:
      - test:destroy
    cmds:
      - docker-compose -p makeen_test -f docker-compose.testing.yml down -v
